const DocGenerator = require('../src/generators/docGenerator');
const fs = require('fs');
const path = require('path');

/**
 * generate-doc.js - Génère ou régénère la documentation OpenAPI
 * 
 * Ce script utilise les routes déjà parsées et enrichies par index-project.js
 * pour générer la documentation OpenAPI.
 * 
 * Utilisation typique:
 * - Après index-project.js (génère automatiquement)
 * - Pour régénérer la doc avec des options différentes
 * - Pour exporter dans un format spécifique
 */

// Parse command line arguments
const args = process.argv.slice(2);
const options = {
  routes: null,
  output: null,
  format: 'openapi' // openapi, swagger, json
};

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--routes' && args[i + 1]) {
    options.routes = args[i + 1];
    i++;
  } else if (args[i] === '--output' && args[i + 1]) {
    options.output = args[i + 1];
    i++;
  } else if (args[i] === '--format' && args[i + 1]) {
    options.format = args[i + 1];
    i++;
  }
}

// Default paths - uses files generated by index-project.js
const defaultRoutesPath = path.join(__dirname, '..', 'data', 'routes.json');
const defaultOutputPath = path.join(__dirname, '..', 'data', 'generated-openapi.json');

const routesPath = options.routes || defaultRoutesPath;
const outputPath = options.output || defaultOutputPath;

console.log('📄 Génération de Documentation OpenAPI\n');
console.log('==========================================================================\n');
console.log(`📁 Fichier routes: ${routesPath}`);
console.log(`📁 Fichier sortie: ${outputPath}\n`);

// Load routes
if (!fs.existsSync(routesPath)) {
  console.error(`❌ Fichier routes non trouvé: ${routesPath}`);
  console.error('   Exécutez d\'abord: node scripts/index-project.js <path>');
  process.exit(1);
}

const routesData = JSON.parse(fs.readFileSync(routesPath, 'utf-8'));
const routes = Array.isArray(routesData) ? routesData : Object.values(routesData).flat();

console.log(`✅ Chargé ${routes.length} routes\n`);

// Generate OpenAPI documentation
const generator = new DocGenerator();

if (Array.isArray(routesData)) {
  // Simple array of routes
  const openAPIDocs = {
    openapi: '3.0.0',
    info: {
      title: 'Generated API Documentation',
      version: '1.0.0',
      description: 'Auto-generated from Express routes'
    },
    paths: {}
  };

  for (const route of routes) {
    if (!route.method || !route.path) continue;

    const pathKey = route.path.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');
    const methodKey = route.method.toLowerCase();

    if (!openAPIDocs.paths[pathKey]) {
      openAPIDocs.paths[pathKey] = {};
    }

    openAPIDocs.paths[pathKey][methodKey] = {
      summary: route.llmEnrichment?.summary || route.description || `Endpoint ${route.method} ${route.path}`,
      description: route.description || route.llmEnrichment?.description || '',
      tags: route.llmEnrichment?.tags || [route.framework || 'api'],
      parameters: buildParameters(route),
      responses: route.llmEnrichment?.responses || buildDefaultResponses(route)
    };
  }

  // Save output
  fs.writeFileSync(outputPath, JSON.stringify(openAPIDocs, null, 2));
  console.log(`✅ Documentation sauvegardée: ${outputPath}`);
  console.log(`   Routes documentées: ${Object.keys(openAPIDocs.paths).length}\n`);
} else {
  // Grouped by file format (routes-by-file.json)
  console.log('📂 Format groupé par fichier détecté\n');
  
  let totalRoutes = 0;
  let totalPaths = 0;
  
  for (const [file, fileRoutes] of Object.entries(routesData)) {
    console.log(`  Traitement: ${file} (${fileRoutes.length} routes)`);
    totalRoutes += fileRoutes.length;
  }
  
  // Generate combined OpenAPI
  const openAPIDocs = {
    openapi: '3.0.0',
    info: {
      title: 'Generated API Documentation',
      version: '1.0.0',
      description: 'Auto-generated from Express routes - Multi-file project'
    },
    paths: {}
  };

  for (const [file, fileRoutes] of Object.entries(routesData)) {
    for (const route of fileRoutes) {
      if (!route.method || !route.path) continue;

      const pathKey = route.path.replace(/:([a-zA-Z0-9_]+)/g, '{$1}');
      const methodKey = route.method.toLowerCase();

      if (!openAPIDocs.paths[pathKey]) {
        openAPIDocs.paths[pathKey] = {};
      }

      openAPIDocs.paths[pathKey][methodKey] = {
        summary: route.llmEnrichment?.summary || route.description || `Endpoint ${route.method} ${route.path}`,
        description: route.description || route.llmEnrichment?.description || '',
        tags: route.llmEnrichment?.tags || [route.framework || 'api'],
        parameters: buildParameters(route),
        responses: route.llmEnrichment?.responses || buildDefaultResponses(route)
      };
    }
  }

  // Save output
  fs.writeFileSync(outputPath, JSON.stringify(openAPIDocs, null, 2));
  console.log(`\n✅ Documentation sauvegardée: ${outputPath}`);
  console.log(`   Total routes: ${totalRoutes}`);
  console.log(`   Routes documentées: ${Object.keys(openAPIDocs.paths).length}\n`);
}

function buildParameters(route) {
  const params = [];

  if (route.parameters) {
    for (const param of route.parameters) {
      params.push({
        name: param.name,
        in: param.in || 'path',
        required: param.required !== false,
        schema: { type: param.type || 'string' },
        description: param.description || `${param.name} parameter`
      });
    }
  }

  if (route.llmEnrichment?.inputSchema?.query) {
    for (const [name, schema] of Object.entries(route.llmEnrichment.inputSchema.query)) {
      params.push({
        name,
        in: 'query',
        required: schema.required || false,
        schema: { type: schema.type || 'string' },
        description: schema.description || `${name} query parameter`
      });
    }
  }

  return params;
}

function buildDefaultResponses(route) {
  return {
    '200': {
      description: 'Success',
      content: {
        'application/json': {
          schema: route.llmEnrichment?.outputSchema || { type: 'object' }
        }
      }
    },
    '404': { description: 'Not found' },
    '500': { description: 'Server error' }
  };
}

console.log('📖 UTILISATION:\n');
console.log('   node scripts/generate-doc.js [options]\n');
console.log('   Options:');
console.log('   --routes <path>   Fichier routes source (défaut: data/routes.json)');
console.log('   --output <path>  Fichier de sortie (défaut: data/generated-openapi.json)');
console.log('   --format <type>  Format de sortie (défaut: openapi)');
console.log('\n   Exemples:');
console.log('   node scripts/generate-doc.js');
console.log('   node scripts/generate-doc.js --routes data/routes.json --output data/my-api.json');
console.log('\n✅ Terminé!');
